FROM node:lts-alpine

WORKDIR /api

COPY package*.json ./
RUN yarn install
# We copy the whole dir instead of only "./src" because otherwise directories
# with test files won't be included
COPY . .

CMD yarn run migratesql up && yarn run serve:dev
