#!/bin/bash

curl \
  --include \
  --request PATCH \
  --header "content-type: application/json" \
  --data '{"email":"info@andreyponomarev.ru"}' \
  http://localhost:5000/api/v1/users/settings/password

echo
