#!/bin/bash

curl \
  --include \
  --no-buffer \
  --header "connection: upgrade" \
  --header "upgrade: websocket" \
  --header "host: localhost:5000" \
  --header "origin: http://localhost:5000" \
  --header "sec-websocket-key: zy6Dy9mSAIM7GJZNf9rI1A==" \
  --header "sec-websocket-version: 13" \
  http://localhost:5000

echo

# If the response is some error, try to change the string in 'sec-websocket-key', I don't know why but somehow that helped me the previous time — it was too short and after replacing with a longer string, I get the successful response

# If curl hangs after recieving the response, it's OK and is expected behavior. Here is how you can fix this if you need: https://stackoverflow.com/questions/47353406/websocket-server-health-check-with-curl
